// Current public FutureLens.cloud collection, verified 24 September 2026.
// Keep this a curated portfolio: all destinations are independent public tours.
export const tours = [
  { slug: 'white-lotus', name: 'White Lotus', location: 'Virginia', kind: '3D + 360°', image: '/tours/white-lotus.jpg', alt: 'The White Lotus treehouse in daylight', note: 'A treehouse, a quiet retreat, and a different way of seeing the grounds.', url: 'https://white-lotus-digital-twin.netlify.app/#place=treehouse&view=model' },
  { slug: 'monticello', name: 'Monticello', location: 'Charlottesville, Virginia', kind: '3D reconstruction', image: '/tours/monticello.webp', alt: 'Digital reconstruction of Monticello and its surrounding landscape', note: 'Architecture, terrain, and history, brought together in an independent reconstruction.', url: 'https://monticello-digital-twin.netlify.app/' },
  { slug: 'ix-art-park', name: 'IX Art Park', location: 'Charlottesville, Virginia', kind: '3D + stories', image: '/tours/ix-art-park.jpg', alt: 'The colorful courtyard at IX Art Park', note: 'A place where art spills outside. A world you can wander through.', url: 'https://ix-art-park-tour.netlify.app/' },
  { slug: 'big-hollow-greene', name: 'Big Hollow Greene', location: 'Maplecrest, New York', kind: '3D + interiors', image: '/tours/big-hollow-greene.jpg', alt: 'Big Hollow Greene in the Catskills', note: 'The Catskills campus, farmhouse interiors, and room to imagine what comes next.', url: 'https://bighollowgreene-tour.netlify.app/' },
  { slug: 'forest-city-farms', name: 'Forest City Farms', location: 'Whately, Massachusetts', kind: '3D + 360°', image: '/tours/forest-city-farms.jpg', alt: 'Forest City Farms and its growing spaces', note: 'Across the fields and inside the greenhouses. A closer look at a working farm.', url: 'https://forestcityfarms.netlify.app/' },
  { slug: 'alan-day', name: 'Alan Day Community Garden', location: 'Norway, Maine', kind: '3D + stories', image: '/tours/alan-day.webp', alt: 'Alan Day Community Garden', note: 'A community garden, its gathering spaces, and the people growing something together.', url: 'https://alanday.netlify.app/' },
  { slug: 'bridge-between-the-worlds', name: 'Bridge Between the Worlds', location: 'Keswick, Virginia', kind: '3D + 360°', image: '/tours/bridge-between-the-worlds.jpg', alt: 'The lake and wooded landscape at Bridge Between the Worlds', note: 'A wooded sanctuary. Follow the water, the paths, and the spaces tucked between them.', url: 'https://bridgebetweentheworlds.netlify.app/' },
  { slug: 'oya', name: 'OYA', location: 'Dominican Republic', kind: '360° exploration', image: '/tours/oya.webp', alt: 'The tropical grounds of OYA', note: 'A journey through tropical landscapes, connected one panorama at a time.', url: 'https://oya-360-tour.netlify.app/' },
  { slug: 'downtown-mall', name: 'Downtown Mall', location: 'Charlottesville, Virginia', kind: '3D atlas + 360°', image: '/tours/charlottesville-downtown-mall.webp', alt: 'Digital reconstruction of Charlottesville Downtown Mall over aerial imagery', note: 'The city at walking pace, explored through maps, stories, and a reconstructed streetscape.', url: 'https://charlottesville-downtown-mall.netlify.app/#overview' },
  { slug: 'chozen', name: 'ChoZen', location: 'Sebastian, Florida', kind: '3D + 360°', image: '/tours/chozen.jpg', alt: 'The lawn and outdoor gathering space at ChoZen’s Harvest House', note: 'From the Harvest House lawn into the retreat, through original 360° photography.', url: 'https://chozen-digital-twin.netlify.app/#scene=018' },
] as const;
